//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bumper
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public machine()
        {
            this.incidence = new HashSet<incidence>();
        }
    
        public int id { get; set; }
        public string provider { get; set; }
        public string instance { get; set; }
        public string tag { get; set; }
        public string domain { get; set; }
        public string publicips { get; set; }
        public string privateips { get; set; }
        public string environment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incidence> incidence { get; set; }
    }
}
